extends Node


const PLAYER_LAYER := 1
const ENEMY_LAYER := 2
const ENVIRONMENT_LAYER := 4
const BEAM_LAYER := 8
const INITIAL_ENERGY := 30
const PLAYER_INVINCIBILITY_TIME := 2
const ENEMY_INVINCIBILITY_TIME := 0.2
const HITSTOP_TIME := 0.2
const DELAY_BETWEEN_SHOTS := 0.13
